require 'net/http'
require 'uri'

class LoadBalancer
  BACKENDS = ['http://localhost:4567', 'http://localhost:4568', 'http://localhost:4569', 'http://localhost:4570']
  ACTIVE_BACKENDS = BACKENDS.dup

  def initialize
    @index = 0
    @mutex = Mutex.new
  end

  def call(env)
    backend = next_backend
    req = Rack::Request.new(env)
    forward(req, backend)
  end

  private

  def next_backend
    @mutex.synchronize do
      backend = ACTIVE_BACKENDS[@index % ACTIVE_BACKENDS.size]
      @index += 1
      backend
    end
  end

  def forward(req, backend)
    uri = URI.parse(backend + req.fullpath)

    http = Net::HTTP.new(uri.host, uri.port)

    # Build the outgoing request
    out_req = Net::HTTP.const_get(req.request_method.capitalize).new(uri.request_uri)

    # Copy headers
    req.env.each do |key, val|
      next unless key.start_with?('HTTP_')
      header = key.sub('HTTP_', '').gsub('_', '-').downcase
      out_req[header] = val
    end

    # Copy body for mutating methods
    if %w[POST PUT PATCH].include?(req.request_method)
      out_req.body = req.body.read
      out_req.content_type = req.content_type
    end

    resp = http.request(out_req)

    # This was generated by Claude AI but it seems to be right:
    # "Hop-by-hop headers are HTTP headers designed to be processed or consumed
    # by the immediate proxy or cache in the network path, rather than the final, end-to-end destination."
    # https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers#hop-by-hop_headers
    # Filter out hop-by-hop headers
    headers = resp.each_header.to_h.reject do |k, _|
      %w[transfer-encoding connection keep-alive].include?(k.downcase)
    end

    [resp.code.to_i, headers, [resp.body]]

  rescue Errno::ECONNREFUSED
    ACTIVE_BACKENDS.delete(backend)
    [500, {}, ["Backend #{backend} is not available"]]
  end
end
